spring:
  application:
    name: stocktracker
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: h2
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
